FROM node:18

ARG VITE_BASE_URL_BACKEND=http://localhost:8081
ENV VITE_BASE_URL_BACKEND=$VITE_BASE_URL_BACKEND

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm", "start"]
